kind: StorageCluster
apiVersion: core.libopenstorage.org/v1
metadata:
  name: px-cluster
  namespace: portworx
  annotations:
    portworx.io/is-openshift: "true"
    portworx.io/is-eks: "true"
    portworx.io/misc-args: " -T px-storev2 "
    portworx.io/preflight-check: "true"
    portworx.io/portworx-proxy: "false"
spec:
  image: docker.io/portworx/oci-monitor:3.6.2.2
  imagePullPolicy: Always
  kvdb:
    internal: true
    enableTLS: true
  cloudStorage:
    deviceSpecs:
    - type=gp3,size=150
    systemMetadataDeviceSpec: type=gp3,size=64
  secretsProvider: k8s
  startPort: 17001
  stork:
    enabled: true
    args:
      webhook-controller: "true"
  autopilot:
    enabled: true
  runtimeOptions:
    default-io-profile: "6"
  csi:
    enabled: true
  monitoring:
    telemetry:
      enabled: true
    prometheus:
      enabled: true
      exportMetrics: true
  certManager:
    enabled: true
  env:
  - name: AWS_ACCESS_KEY_ID
    valueFrom: {secretKeyRef: {name: pgaikwad-px-rosa-px-aws-creds, key: aws-key}}
  - name: AWS_SECRET_ACCESS_KEY
    valueFrom: {secretKeyRef: {name: pgaikwad-px-rosa-px-aws-creds, key: aws-secret}}
