//go:build !ignore_autogenerated

/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageBasedRemediation) DeepCopyInto(out *StorageBasedRemediation) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageBasedRemediation.
func (in *StorageBasedRemediation) DeepCopy() *StorageBasedRemediation {
	if in == nil {
		return nil
	}
	out := new(StorageBasedRemediation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StorageBasedRemediation) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageBasedRemediationConfig) DeepCopyInto(out *StorageBasedRemediationConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageBasedRemediationConfig.
func (in *StorageBasedRemediationConfig) DeepCopy() *StorageBasedRemediationConfig {
	if in == nil {
		return nil
	}
	out := new(StorageBasedRemediationConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StorageBasedRemediationConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageBasedRemediationConfigList) DeepCopyInto(out *StorageBasedRemediationConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]StorageBasedRemediationConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageBasedRemediationConfigList.
func (in *StorageBasedRemediationConfigList) DeepCopy() *StorageBasedRemediationConfigList {
	if in == nil {
		return nil
	}
	out := new(StorageBasedRemediationConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StorageBasedRemediationConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageBasedRemediationConfigSpec) DeepCopyInto(out *StorageBasedRemediationConfigSpec) {
	*out = *in
	if in.SharedStorageVolumeMode != nil {
		in, out := &in.SharedStorageVolumeMode, &out.SharedStorageVolumeMode
		*out = new(SharedStorageVolumeModeType)
		**out = **in
	}
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.SBRTimeoutSeconds != nil {
		in, out := &in.SBRTimeoutSeconds, &out.SBRTimeoutSeconds
		*out = new(int32)
		**out = **in
	}
	if in.MaxConsecutiveFailures != nil {
		in, out := &in.MaxConsecutiveFailures, &out.MaxConsecutiveFailures
		*out = new(int32)
		**out = **in
	}
	if in.DetectOnlyMode != nil {
		in, out := &in.DetectOnlyMode, &out.DetectOnlyMode
		*out = new(DetectOnlyModeType)
		**out = **in
	}
	if in.IoTimeout != nil {
		in, out := &in.IoTimeout, &out.IoTimeout
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageBasedRemediationConfigSpec.
func (in *StorageBasedRemediationConfigSpec) DeepCopy() *StorageBasedRemediationConfigSpec {
	if in == nil {
		return nil
	}
	out := new(StorageBasedRemediationConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageBasedRemediationConfigStatus) DeepCopyInto(out *StorageBasedRemediationConfigStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageBasedRemediationConfigStatus.
func (in *StorageBasedRemediationConfigStatus) DeepCopy() *StorageBasedRemediationConfigStatus {
	if in == nil {
		return nil
	}
	out := new(StorageBasedRemediationConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageBasedRemediationConfigValidator) DeepCopyInto(out *StorageBasedRemediationConfigValidator) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageBasedRemediationConfigValidator.
func (in *StorageBasedRemediationConfigValidator) DeepCopy() *StorageBasedRemediationConfigValidator {
	if in == nil {
		return nil
	}
	out := new(StorageBasedRemediationConfigValidator)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageBasedRemediationList) DeepCopyInto(out *StorageBasedRemediationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]StorageBasedRemediation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageBasedRemediationList.
func (in *StorageBasedRemediationList) DeepCopy() *StorageBasedRemediationList {
	if in == nil {
		return nil
	}
	out := new(StorageBasedRemediationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StorageBasedRemediationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageBasedRemediationSpec) DeepCopyInto(out *StorageBasedRemediationSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageBasedRemediationSpec.
func (in *StorageBasedRemediationSpec) DeepCopy() *StorageBasedRemediationSpec {
	if in == nil {
		return nil
	}
	out := new(StorageBasedRemediationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageBasedRemediationStatus) DeepCopyInto(out *StorageBasedRemediationStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageBasedRemediationStatus.
func (in *StorageBasedRemediationStatus) DeepCopy() *StorageBasedRemediationStatus {
	if in == nil {
		return nil
	}
	out := new(StorageBasedRemediationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageBasedRemediationTemplate) DeepCopyInto(out *StorageBasedRemediationTemplate) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageBasedRemediationTemplate.
func (in *StorageBasedRemediationTemplate) DeepCopy() *StorageBasedRemediationTemplate {
	if in == nil {
		return nil
	}
	out := new(StorageBasedRemediationTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StorageBasedRemediationTemplate) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageBasedRemediationTemplateList) DeepCopyInto(out *StorageBasedRemediationTemplateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]StorageBasedRemediationTemplate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageBasedRemediationTemplateList.
func (in *StorageBasedRemediationTemplateList) DeepCopy() *StorageBasedRemediationTemplateList {
	if in == nil {
		return nil
	}
	out := new(StorageBasedRemediationTemplateList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StorageBasedRemediationTemplateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageBasedRemediationTemplateResource) DeepCopyInto(out *StorageBasedRemediationTemplateResource) {
	*out = *in
	out.Spec = in.Spec
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageBasedRemediationTemplateResource.
func (in *StorageBasedRemediationTemplateResource) DeepCopy() *StorageBasedRemediationTemplateResource {
	if in == nil {
		return nil
	}
	out := new(StorageBasedRemediationTemplateResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageBasedRemediationTemplateSpec) DeepCopyInto(out *StorageBasedRemediationTemplateSpec) {
	*out = *in
	out.Template = in.Template
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageBasedRemediationTemplateSpec.
func (in *StorageBasedRemediationTemplateSpec) DeepCopy() *StorageBasedRemediationTemplateSpec {
	if in == nil {
		return nil
	}
	out := new(StorageBasedRemediationTemplateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageBasedRemediationTemplateStatus) DeepCopyInto(out *StorageBasedRemediationTemplateStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageBasedRemediationTemplateStatus.
func (in *StorageBasedRemediationTemplateStatus) DeepCopy() *StorageBasedRemediationTemplateStatus {
	if in == nil {
		return nil
	}
	out := new(StorageBasedRemediationTemplateStatus)
	in.DeepCopyInto(out)
	return out
}
